name: A Workflow
on:
  push:
    branches:
      - main
jobs:
    AJob:
      runs-on: ubuntu-latest

      steps:
        - run: echo "👋 Hello World!"

        - name: Checkout
          uses: actions/checkout@v4.1.0


        - name: List files in repository
          run: |
            echo "The repository ${{ github.repository }} contains the following files:"
            tree
